### ISSUE TITLE
How good is your graphics performance

### ISSUE THREAD

**Issue by danielehrhardt** [Ken5998/OpenCore-VMware-Workstation-AMD#1]
Hi,
you can close this Issue if you want.
I want to ask how good your graphics performance is with this VM?

**Comment by Ken5998** [comment]
> Hi,
> you can close this Issue if you want.
> I want to ask how good your graphics performance is with this VM?

Hi, actually with the VMware Tools you can get 128MB of graphics memory that is not good as a dedicated GPU but is usable to do some basic stuff :)
Unfortunately, it doesn't have hardware acceleration and as a result there are sometimes lags or freezes if you perform complex tasks.

**Comment by danielehrhardt** [comment]
Thank you for your Feedback 👍
