### ISSUE TITLE
USB boots into Apple logo instead of OpenCore

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [Ken5998/OpenCore-VMware-Workstation-AMD#2]
I've followed the steps exactly, but when I'm actually trying to install macOS from the USB stick I've created, instead of OpenCore menu I get an Apple logo immediately, and after a while, an error saying "The CPU has been disabled by the guest operating system". What could be the problem?

**Comment by Ken5998** [comment]
> I've followed the steps exactly, but when I'm actually trying to install macOS from the USB stick I've created, instead of OpenCore menu I get an Apple logo immediately, and after a while, an error saying "The CPU has been disabled by the guest operating system". What could be the problem?

Hi, you can try to add the following option to your .vmx file (you can find it in the same folder of the VM) to wait 5 seconds and so you can press the boot option key.

bios.bootDelay = "5000"

(5000 -> 5 seconds) you can change it to a max of 10 seconds

**Comment by ZimM-LostPolygon** [comment]
@Ken5998 Solved it! I had to copy the entire EFI folder into the EFI partitions, not the contents of the EFI folder.
