### ISSUE TITLE
Audio does not work

### ISSUE THREAD

**Issue by makoONE** [Ken5998/OpenCore-VMware-Workstation-AMD#3]
Audio does not work according to your instructions.
No devices are detected for sound output.
Do you know what to do to activate audio?

**Comment by Ken5998** [comment]
I haven't found a functional solution yet.
I also tried with the VoodooHDA kext that detects the audio device but nothing is heard anyway.

**Comment by Ken5998** [comment]
> Audio does not work according to your instructions.
> No devices are detected for sound output.
> Do you know what to do to activate audio?

My bad, I found a solution.
You need to remove the AppleALC.kext from the EFI folder.
Then download VoodooHDA from here: https://github.com/chris1111/VoodooHDA-OC and install it.
After that reboot and select the SPDIF-out from the audio outputs, but the audio it's non perfectly clear...

**Comment by makoONE** [comment]
Thanks for the voodoo solution. In principle it works with it only unfortunately with some distortions, as you have already noted.
I would have preferred to get it to work with AppleALC but despite hours of trying I couldn't get it to work either.
