### ISSUE TITLE
CPU disabled by Guest OS

### ISSUE THREAD

**Issue by TheColin21** [Ken5998/OpenCore-VMware-Workstation-AMD#4]
I just tried your tutorial with the slight change that I wanted to use a VMDK instead of a USB. I attached a second disk to my existing MacOS 10.15 VM, ran createinstallmedia on it, mounted the EFI, copied the files from this repositories EFI folder there, then created a new VM and attached the VMDK there. The VM tried to boot but the standard "The CPU has been disabled by the guest operating system." error occured. What did I do wrong?

**Comment by TheColin21** [comment]
VMware Workstation 16.1 on an AMD Ryzen 3600 btw.

**Comment by Ken5998** [comment]
> I just tried your tutorial with the slight change that I wanted to use a VMDK instead of a USB. I attached a second disk to my existing MacOS 10.15 VM, ran createinstallmedia on it, mounted the EFI, copied the files from this repositories EFI folder there, then created a new VM and attached the VMDK there. The VM tried to boot but the standard "The CPU has been disabled by the guest operating system." error occured. What did I do wrong?

I have also tried with the VMDK file ad it works normally like the USB... Now I'm uploading the VMDK and I will share with you as soon as it finishes :)
P.S are you sure that have you copied the EFI folder to the "VMDK" volume? Because the patch for the AMD CPU are located inside the EFI folder

**Comment by Ken5998** [comment]
Here is the link: https://drive.google.com/file/d/10qLPTret3KoV1bMRrcHNqKoN7mHvn2-6/view?usp=sharing
Let me know if this works.
For clarify I have created a new VM with a 128GB SATA disk and after the creation I have attached the VMDK that contain the macOS installer.

**Comment by TheColin21** [comment]
Thanks a lot. Yes I also mounted it in windows to check.

Am 15. Januar 2021 16:35:07 MEZ schrieb Kenan Kasumovic <notifications@github.com>:

**Comment by TheColin21** [comment]
I am downloading your VMDK right now. I'll let you know if this VMDK
booted. I'll also recreate my BigSur VM (as I tinkered quite a bit with the
VMX to see if I could get it going) so nothing else can go wrong.

Am Fr., 15. Jan. 2021 um 17:02 Uhr schrieb Colin P <colin.pohle@gmail.com>:

**Comment by TheColin21** [comment]
Update: the installer is booting. I guess I did something wrong, although I
have no idea what it could be.

Am Sa., 16. Jan. 2021 um 10:07 Uhr schrieb Colin P <colin.pohle@gmail.com>:

**Comment by TheColin21** [comment]
BigSur installed just fine, thank you. Is this kind of installation
updatable?

Am Sa., 16. Jan. 2021 um 10:35 Uhr schrieb Colin P <colin.pohle@gmail.com>:

**Comment by Ken5998** [comment]
Perfetct, you're welcome.
Yes now because of the patch for the CPU you can update the VM like a "normal" Mac.

**Comment by tylerwolf35** [comment]
Hi, I am getting the same error, when you say copy the EFI to the VMDK do you mean copy to the install location as well, as I have done that.

**Comment by tylerwolf35** [comment]
I can also not boot into "OpenCore AMD" from BIOS as it appears to do nothing and flash but I could see it gives an error that it cannot load it. I assume this is an issue with the way I used MountEFI.
