### ISSUE TITLE
CPU has been disable

### ISSUE THREAD

**Issue by VoXaN24** [Ken5998/OpenCore-VMware-Workstation-AMD#5]
![image](https://img.vhost.cf/8r3bzlfi.png)
My EFI Disk:
![image](https://img.vhost.cf/hv97onnp.png)
I have extracted the archive in the Disk,

My config :
![image](https://img.vhost.cf/y6nfn82w.png)

Idk what's wrong like i let the vm reboot like 10 min before transfers in the EFI Folder (It's write it can be reboot a lot of time but like more than 10 min of reboot ?)

**Comment by Ken5998** [comment]
Sorry but I haven't undersanded your problem :(
If the problem is the first screenshot, have you tried changing the order in the VMware bios and setting your USB as first one?

**Comment by VoXaN24** [comment]
I use the vmdk file, and i have install it reboot
like it look like made a bootloop, so i put the file in the EFI drive and select it in the BIOS, set to the 1st pos. and booted in it
(My english is verry bad, thx french school btw)

**Comment by Ken5998** [comment]
So now the problem is solved, correct?

**Comment by VoXaN24** [comment]
Nope

**Comment by Ken5998** [comment]
Maybe you can try using some translator like DeepL or Google Translate? :)
The "CPU has been disable" comes out when the VM can't find the EFI folder with the patches for the AMD CPUs.
Have you tried using only the VMDK installer without you EFI drive?

**Comment by xhd4** [comment]
I had 2 problems, one of which was similar to yours.
I think you should try porting the EFI from the vmdk installation to your installed operating system. You will have to do something like this, first mount the EFI installer vmdk using MountEFI and copy the EFI to the desktop, for example, then mount the EFI of the installed system and copy or replace the EFI from the desktop. Next you can unmount the installation vmdk

**Comment by VoXaN24** [comment]
Oh ... Yes i have set in the EFI of the Installed MacOS, i need to set in the Install disk too tho ?

**Comment by VoXaN24** [comment]
This time, the VM Boot UP in MacOS but after i modfied the UEFI (Like it's wrote) it never doing back in it 
![image](https://img.vhost.cf/o0iu9iak.png)

**Comment by Ken5998** [comment]
Ok now you're almost ok.

You need to follow this part:
**_OpenCore entry into the VM BIOS_**

Select the VM and near the Power button select **Power On to Firmware** from the dropdown list

Select Enter setup
Configure boot options
Delete boot option -> remove OpenCore (this is the OpenCore from the USB or VMDK installer)
Add boot option -> search for EFI, [PciRoot... and select it
Select -> BOOTx64.efi
Input the description -> insert something like OpenCore AMD or just Opencore
Commit changes and exit
Select Configure boot options
Change boot order -> set the OpenCore entry at first position, then Commit changes and exit
Exit the Boot Maintenance Manager
Select OpenCore and boot to macOS

**Comment by VoXaN24** [comment]
I have made that but it didn't work, i record what i made maybe i made a thing wrong ASAP (Maybe tomorrow)

**Comment by VoXaN24** [comment]
Ok i have only install from the VMDK (I havn't removed from the disk list), install VMWare addon and it work fine !
