### ISSUE TITLE
Mac OS guest might run unreliably with more than one virtual core

### ISSUE THREAD

**Issue by vitormf** [Ken5998/OpenCore-VMware-Workstation-AMD#7]
![Capture](https://user-images.githubusercontent.com/710828/105756477-710f6980-5f2b-11eb-9226-01ba0ab73100.PNG)

Hey @Ken5998 ,

First of all, thanks for sharing your EFI. I was almost giving up trying to virtualize mac os on a new ryzen cpu until I came up to your page. 👍 
I've been able to make it thank to you 🙏 

The issue I'm seeing is this popup that shows every time the machine boots, but I'm able to continue and boot it.
The system works mostly fine, but every now and then it freezes, maybe once a day.

I'm running on vmware workstation 15 pro - 15.5.7 build-17171714
On a ryzen 5900x

Do you have any idea on what might be causing that? 🙏 

(btw using one core only as the dialog suggests doesn't boot at all)

Best

**Comment by Ken5998** [comment]
Hi @vitormf, thank you very much. You're welcome :)

Sincerely I haven't never seen this issue :(

I have found this [first website ](https://www.beejblog.com/2016/06/esxi-for-winmac-xamarin-ios-dev-nirvana.html) and [second website](https://www.insanelymac.com/forum/topic/290949-how-to-install-os-x-10x-snow-leopard-to-el-capitan-in-vmware-workstation-1011-workstation-proplayer-12-player-67-esxi-56/) and they mentions your issue, you can try adding: `isolation.tools.bug328986.disable = "TRUE"` to the end of the VMX file.
It seems that this just remove the message and nothing else.
I don't know if this little workaround can help you, but you can try and for security make a backup of you current VMX file.

**Comment by vitormf** [comment]
Yup. that does it. Thank you. 🙏
