### ISSUE TITLE
Copy EFI?

### ISSUE THREAD

**Issue by sShrek1** [Ken5998/OpenCore-VMware-Workstation-AMD#9]
Maybe noob question here - but guess I am not the only one ;)

I currently have issues with my CPU gets disabled and the solution should be copy EFI, but can't get that to work.

Overview of what I've done:
* Created VM
* created new hårdare (attached vmdk)
* Boot > install MacOS> erase HDD > install
* Second boot it fails with CPU disabled error.

Here on i don't know how to replace the content from USB (where downloaded EFI is). 
So how should I copy it? Anyone with more noob-friendly instructions? 
Going to recovery and try to mount EFI disk and my USB doesn't work - so copy won't do it.

**Comment by Ken5998** [comment]
> Maybe noob question here - but guess I am not the only one ;)
> 
> I currently have issues with my CPU gets disabled and the solution should be copy EFI, but can't get that to work.
> 
> Overview of what I've done:
> 
> * Created VM
> * created new hårdare (attached vmdk)
> * Boot > install MacOS> erase HDD > install
> * Second boot it fails with CPU disabled error.
> 
> Here on i don't know how to replace the content from USB (where downloaded EFI is).
> So how should I copy it? Anyone with more noob-friendly instructions?
> Going to recovery and try to mount EFI disk and my USB doesn't work - so copy won't do it.

The USB flash drive is required until you get to the Big Sur home screen (to the configuration page, language, and user settings).

You have to change the boot order in the VMware BIOS.
Select the VM and near the Power button select Power On to Firmware from the dropdown list
(check if in to the boot order already exists a OpenCore entry, if exist set it to the first position)

- Select Enter setup
- Configure boot options
- Add boot option -> search for EFI, [PciRoot... and select it
- Select -> -> BOOTx64.efi
- Input the description -> insert something like Opencore
- Commit changes and exit
- Select Configure boot options
- Change boot order -> set the OpenCore entry at first position, then Commit changes and exit
- Exit the Boot Maintenance Manager
- Select OpenCore and boot to macOS

**Comment by Ken5998** [comment]
> > The USB flash drive is required until you get to the Big Sur home screen (to the configuration page, language, and user settings).
> > You have to change the boot order in the VMware BIOS.
> > Select the VM and near the Power button select Power On to Firmware from the dropdown list
> > (check if in to the boot order already exists a OpenCore entry, if exist set it to the first position)
> > 
> > * Select Enter setup
> > * Configure boot options
> > * Add boot option -> search for EFI, [PciRoot... and select it
> > * Select -> -> BOOTx64.efi
> > * Input the description -> insert something like Opencore
> > * Commit changes and exit
> > * Select Configure boot options
> > * Change boot order -> set the OpenCore entry at first position, then Commit changes and exit
> > * Exit the Boot Maintenance Manager
> > * Select OpenCore and boot to macOS
> 
> At this point, should I unattach the attached vmdk (preinstalled one)?
> Selecting "Power on to firmware" gives me OpenCore Boot menu, which one should I select? (already done 1. Install macOS)
> ![image](https://user-images.githubusercontent.com/18519443/117536833-a97c1480-affd-11eb-903b-670e5f9d65dc.png)

No because the installation are not finished yet. It takes about 3-4 reboot to complete the installation.
